#!/bin/bash
# ci-env start — unified entry point for all topologies.
# Usage: bash start.sh [fp-mock|fp-tz|fp-full] [--tz] [--mock] [-m|--monitoring] [--env <file>]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/common.sh"

PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DATA="$PROJECT_ROOT/dev/data"
DEV_CONFIGS="$PROJECT_ROOT/dev/config"
FP_COMPOSE="$PROJECT_ROOT/fault-proof/docker-compose.yml"

TOPOLOGY="fp-mock"
TZ_MODE=0
MOCK_MODE=0
MONITORING=0
BUILD_ONLY=0
CUSTOM_ENV=""
FAILED_SERVICES=()

# Parse args
while [ $# -gt 0 ]; do
  case "$1" in
    fp-mock|fp-tz|fp-full) TOPOLOGY="$1" ;;
    --tz) TZ_MODE=1 ;;
    --mock) MOCK_MODE=1 ;;
    -m|--monitoring) MONITORING=1 ;;
    --build-only) BUILD_ONLY=1 ;;
    --env) shift; CUSTOM_ENV="$1" ;;
    *) warn "Unknown arg: $1" ;;
  esac
  shift
done

# Topology implies defaults
case "$TOPOLOGY" in
  fp-mock) MOCK_MODE=1 ;;
  fp-tz)   TZ_MODE=1 ;;
  fp-full) MONITORING=1 ;;
esac

# Save script-level flags before env file may overwrite them
_MOCK=$MOCK_MODE
_TZ=$TZ_MODE
_MON=$MONITORING
_BUILD_ONLY=$BUILD_ONLY

mkdir -p "$DATA"

resolve_env() {
  if [ -n "$CUSTOM_ENV" ]; then
    echo "$CUSTOM_ENV"
  else
    echo "$DEV_CONFIGS/$TOPOLOGY.env"
  fi
}

proposer_bin() {
  if [ "$TZ_MODE" -eq 1 ]; then echo "tz-proposer"; else echo "proposer"; fi
}

challenger_bin() {
  if [ "$TZ_MODE" -eq 1 ]; then echo "tz-challenger"; else echo "challenger"; fi
}

build() {
  local prop; prop=$(proposer_bin)
  local chal; chal=$(challenger_bin)
  local features=""
  [ "$TZ_MODE" -eq 1 ] && features="--features tz"

  info "Building $prop + $chal (release${features:+, $features})..."
  cd "$PROJECT_ROOT"
  mkdir -p target/tmp
  # TMPDIR override: fixes SP1 nested build writing to read-only registry dir
  TMPDIR="$(pwd)/target/tmp" CARGO_TARGET_DIR="$(pwd)/target" \
    cargo build --bin "$prop" --bin "$chal" --release $features
  ok "Build complete"
}

start_proposer() {
  local bin_name; bin_name=$(proposer_bin)
  local bin="$PROJECT_ROOT/target/release/$bin_name"
  local pidfile="$DATA/.proposer.pid"
  local log="$DATA/proposer.log"

  if pid_alive "$pidfile"; then
    warn "Proposer already running (PID $(cat "$pidfile")), skipping"
    return 0
  fi

  [ ! -f "$bin" ] && { err "Binary not found: $bin"; return 1; }

  info "Starting $bin_name..."
  launch_bg "$pidfile" "$log" "$bin"
  wait_process "$pidfile" "$bin_name" 5 || { warn "$bin_name exited — check: tail -f $log"; FAILED_SERVICES+=("$bin_name"); }
}

start_challenger() {
  local bin_name; bin_name=$(challenger_bin)
  local bin="$PROJECT_ROOT/target/release/$bin_name"
  local pidfile="$DATA/.challenger.pid"
  local log="$DATA/challenger.log"

  if pid_alive "$pidfile"; then
    warn "Challenger already running (PID $(cat "$pidfile")), skipping"
    return 0
  fi

  [ ! -f "$bin" ] && { err "Binary not found: $bin"; return 1; }

  info "Starting $bin_name..."
  launch_bg "$pidfile" "$log" "$bin"
  wait_process "$pidfile" "$bin_name" 5 || { warn "$bin_name exited — check: tail -f $log"; FAILED_SERVICES+=("$bin_name"); }
}

start_monitoring() {
  info "Starting monitoring (Prometheus + Grafana)..."
  cd "$PROJECT_ROOT/fault-proof"

  # Ensure docker-compose env deps exist
  [ ! -f .env.proposer ] && touch .env.proposer
  [ ! -f .env.challenger ] && touch .env.challenger

  docker compose -f docker-compose.yml up -d prometheus grafana
  wait_port "${FP_PROMETHEUS_PORT:-9090}" "Prometheus" 15 || warn "Prometheus may not be ready"
  wait_port "${FP_GRAFANA_PORT:-3000}" "Grafana" 15 || warn "Grafana may not be ready"
  ok "Monitoring started"
  echo "  Prometheus :${FP_PROMETHEUS_PORT:-9090}"
  echo "  Grafana    :${FP_GRAFANA_PORT:-3000}  (admin/admin)"
}

write_test_env() {
  local prop_port="${PROPOSER_METRICS_PORT:-9000}"
  local chal_port="${CHALLENGER_METRICS_PORT:-9001}"
  cat > "$DATA/.test-env" <<EOF
# Auto-generated by ci-env start.sh — source this before running tests.
export TOPOLOGY=$TOPOLOGY
export L1_RPC=${L1_RPC:-}
export L2_RPC=${L2_RPC:-}
export FACTORY_ADDRESS=${FACTORY_ADDRESS:-}
export ANCHOR_STATE_REGISTRY_ADDRESS=${ANCHOR_STATE_REGISTRY_ADDRESS:-}
export GAME_TYPE=${GAME_TYPE:-}
export MOCK_MODE=${MOCK_MODE:-false}
export PROPOSER_METRICS_PORT=${prop_port}
export CHALLENGER_METRICS_PORT=${chal_port}
EOF
  info "Test env written to dev/data/.test-env"
}

write_topology_marker() {
  echo "$TOPOLOGY" > "$DATA/.topology"
  [ "$_TZ" -eq 1 ] && echo "tz" >> "$DATA/.topology" || true
}

# ── Topology: fp-mock ──────────────────────────────────────────────
do_fp_mock() {
  echo "========================================="
  echo "  fp-mock: Mock proving (zero Docker)"
  echo "========================================="

  local envfile; envfile=$(resolve_env)
  if [ -f "$envfile" ]; then
    load_env "$envfile"
  else
    warn "No env file at $envfile — using current environment"
  fi

  export MOCK_MODE=true

  build
  if [ "$_BUILD_ONLY" -eq 1 ]; then ok "Build-only mode, skipping service start"; return 0; fi

  start_proposer
  start_challenger
  write_test_env
  write_topology_marker

  echo ""
  ok "fp-mock started (MOCK_MODE=true)"
  echo "  Proposer   metrics :${PROPOSER_METRICS_PORT:-9000}"
  echo "  Challenger metrics :${CHALLENGER_METRICS_PORT:-9001}"
  echo "  Logs: tail -f $DATA/proposer.log"
  echo "        tail -f $DATA/challenger.log"
}

# ── Topology: fp-tz ──────────────────────────────────────────────
do_fp_tz() {
  local mock_label=""; [ "$_MOCK" -eq 1 ] && mock_label=" (mock)"
  echo "========================================="
  echo "  fp-tz: TradeZone fault proof${mock_label}"
  echo "========================================="

  local envfile; envfile=$(resolve_env)
  if [ -f "$envfile" ]; then
    load_env "$envfile"
  else
    warn "No env file at $envfile — using current environment"
  fi

  [ "$_MOCK" -eq 1 ] && export MOCK_MODE=true

  build
  if [ "$_BUILD_ONLY" -eq 1 ]; then ok "Build-only mode, skipping service start"; return 0; fi

  start_proposer
  start_challenger
  write_test_env
  write_topology_marker

  if [ "$_MON" -eq 1 ]; then
    start_monitoring
  fi

  echo ""
  ok "fp-tz started"
  echo "  tz-proposer   metrics :${PROPOSER_METRICS_PORT:-9000}"
  echo "  tz-challenger metrics :${CHALLENGER_METRICS_PORT:-9001}"
  echo "  L2 RPC: ${L2_RPC:-<not set>}"
  echo "  Logs: tail -f $DATA/proposer.log"
  echo "        tail -f $DATA/challenger.log"
}

# ── Topology: fp-full ──────────────────────────────────────────────
do_fp_full() {
  local tz_label=""; [ "$_TZ" -eq 1 ] && tz_label=" (tz)"
  echo "========================================="
  echo "  fp-full: Full fault proof + monitoring${tz_label}"
  echo "========================================="

  local envfile; envfile=$(resolve_env)
  if [ -f "$envfile" ]; then
    load_env "$envfile"
  else
    warn "No env file at $envfile — using current environment"
  fi

  build
  if [ "$_BUILD_ONLY" -eq 1 ]; then ok "Build-only mode, skipping service start"; return 0; fi

  start_monitoring
  start_proposer
  start_challenger
  write_test_env
  write_topology_marker

  echo ""
  ok "fp-full started"
  local prop_name; prop_name=$(proposer_bin)
  local chal_name; chal_name=$(challenger_bin)
  echo "  $prop_name   metrics :${PROPOSER_METRICS_PORT:-9000}"
  echo "  $chal_name metrics :${CHALLENGER_METRICS_PORT:-9001}"
  echo "  Prometheus :${FP_PROMETHEUS_PORT:-9090}"
  echo "  Grafana    :${FP_GRAFANA_PORT:-3000}  (admin/admin)"
  echo "  Logs: tail -f $DATA/proposer.log"
  echo "        tail -f $DATA/challenger.log"
}

# ── Dispatch ──────────────────────────────────────────────────────────
case "$TOPOLOGY" in
  fp-mock) do_fp_mock ;;
  fp-tz)   do_fp_tz ;;
  fp-full) do_fp_full ;;
  *) err "Unknown topology: $TOPOLOGY"; exit 1 ;;
esac

# ── Report failed services ───────────────────────────────────────────
if [ "${#FAILED_SERVICES[@]}" -gt 0 ]; then
  echo ""
  warn "Some services failed to stay alive: ${FAILED_SERVICES[*]}"
  warn "Check logs in $DATA/ and verify your env config."
  exit 1
fi
